config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'billboards#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end


  resources :billboards
  resources :billboard_votes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :billboard_votes

  validates :name, :image, presence: true

end

app/models/billboard_vote.rb
class BillboardVote < ApplicationRecord
  belongs_to :billboard
  belongs_to :user

  enum direction: [ :up, :down]
end

app/models/billboard_votes.rb
class BillboardVote < ApplicationRecord
  belongs_to :billboard
  belongs_to :user

  enum direction: [ :up, :down]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_confirmation_of :password

  has_many :billboard_votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/billboard_votes_controller.rb
class BillboardVotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_billboard

  def create
    existing_vote = BillboardVote.where(billboard_id: @billboard.id, user_id: current_user.id).first
    if existing_vote && existing_vote.direction == params[:direction]
      redirect_to billboards_path, notice: "You can't vote #{params[:direction]} twice for the same billboard! :)"
    else
      params[:billboard_vote] = {}
      params[:billboard_vote][:user_id] = current_user.id
      params[:billboard_vote][:billboard_id] = @billboard.id
      params[:billboard_vote][:direction] = params[:direction]
      vote = BillboardVote.new(billboard_vote_params)
      if vote.save
        if vote.direction == 'up'
          @billboard.upvotes += 1
          @billboard.downvotes -= 1 if existing_vote
        else
          @billboard.downvotes += 1
          @billboard.upvotes -= 1 if existing_vote
        end
        @billboard.score = @billboard.upvotes - @billboard.downvotes
        @billboard.save
        redirect_to billboards_path, notice: "Thanks for voting!"
      else
        redirect_to billboards_path, notice: "System error! Please try voting again"
      end
    end
  end

  private

  def billboard_vote_params
    params.required(:billboard_vote).permit(:billboard_id, :user_id, :direction)
  end

  def set_billboard
    begin
      @billboard = Billboard.find(params[:billboard_id])
    rescue ActiveRecord::RecordNotFound
      render json: nil, status: :unprocessable_entity
    end
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    billboards = Billboard.all
    weighted_billboards = []
    billboards.each do |b|
      billboard = {}
      billboard[:id] = b.id
      billboard[:name] = b.name
      billboard[:image] = b.image
      billboard[:score] = b.score
      t = ((Time.now - b.created_at) / 1.hour).round
      billboard[:weighted_score] = b.score / (t + 2)**1.8
      weighted_billboards.push billboard
    end
    @billboards = weighted_billboards.sort_by { |hsh| hsh[:weighted_score] }.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def name_action(value)
    @name_action = value
  end

end

app/views/billboards/index.haml
- title 'Billboards'

.col-xs-12
  .page-header-sans
    %h3
      It's billboard contest time!
    %h4
      Vote up and down on as many billboards as you like!
.col-xs-12
  = render 'layouts/messages'

.col-xs-12
  * Billboard ranking is determined by voting and time since added to the contest

- c = 1
- @billboards.each do |b|
  .row
    .col-xs-12.big-top-margin
      .col-sm-2.padding-top
        .semi-bold
          = '#' + c.to_s + ' ranked'
      .col-sm-2.padding-top
        .semi-bold
          = b[:name]
      .col-sm-4
        = image_tag b[:image], class: "img img-responsive"
      .col-sm-2.padding-top
        .semi-bold
          = 'Overall score: ' + b[:score].to_s
      .col-sm-1.hidden-xs.padding-top
        = button_to 'Upvote', billboard_votes_path, method: :post, params: {billboard_id: b[:id], direction: 'up'}, class: "btn btn-default vote-button"
        = button_to 'Downvote', billboard_votes_path, method: :post, params: {billboard_id: b[:id], direction: 'down'}, class: "btn btn-default vote-button downvote"

      .col-xs-12.hidden-sm.hidden-md.hidden-lg.padding-top
        .left
          = button_to 'Upvote', billboard_votes_path, method: :post, params: {billboard_id: b[:id], direction: 'up'}, class: "btn btn-default vote-button"
        .left
          = button_to 'Downvote', billboard_votes_path, method: :post, params: {billboard_id: b[:id], direction: 'down'}, class: "btn btn-default vote-buttons small-left-margin"
        .clear

  - c+=1

app/views/layouts/_head.haml
%meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name: "viewport"}
%meta{:content => '', name: "description"}
%meta{:content => '', name: "keywords"}
%meta{:content => "on", name: "twitter:widgets:csp"}

/ Le HTML5 shim, for IE6-8 support of HTML5 elements
/[if lt IE 9]
  = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js", :media => "all", "data-turbolinks-track" => true

= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true
= javascript_include_tag "application", "data-turbolinks-track" => true
= csrf_meta_tags

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) && msg != 'You are already signed in.' %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = yield(:title) || 'AdQuickTest'
    = render 'layouts/head'
  %body
    .wrapper
      .container
        .row
          .col-xs-12.zero
            = yield
      .push